server:
    port: 3010

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web3d?serverTimezone=UTC
        username: yzx
        password: zixuanyu
        driver-class-name: com.mysql.cj.jdbc.Driver
    banner:
        charset: UTF-8
        location: classpath:banner.txt


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.springboottest1.entity
